### ISSUE TITLE
u3d.showVideo(); problem at ANDROID

### ISSUE THREAD

**Issue by Gamezhero** [lilili87222/Unity-ANE#2]
I used ANE in iOs & Android
ANE(rewards & video) works great at iOS 
Reward video works great at Android too

but I have problem with video ads on Android

```
if (isSupport())
			{
				if (u3d.isVideoReady())
				{
					initEvents();
					u3d.showVideo();
				}
				else
				{
					handlerFail();
				}
			}
			else
			{
				handlerFail();
			}
```

Don't show ads and don't any events calls on u3d.showVideo();

**Comment by lilili87222** [comment]
handle fail when event onLoadVideoFail received,not check ready .
UnityAds.getInstance().setUnityKeys("game id");
UnityAds.getInstance().addEventListener(UnityAdsEvent.onLoadVideoSuccess, onAdReceived);
UnityAds.getInstance().addEventListener(UnityAdsEvent.onLoadVideoFail, onAdFailReceived);
protected function onAdFailReceived(event:UnityAdsEvent):void
{
//handler fail
}
protected function onAdReceived(event:UnityAdsEvent):void
{
    UnityAds.getInstance().showRewardVideo();
}


package  so.cuo.platform.unity
{
	import flash.events.Event;

	public class UnityAdsEvent extends Event
	{
		public static const  onLoadVideoSuccess:String = "onLoadVideoSuccess";
		public static const  onLoadVideoFail :String= "onLoadVideoFail";
		public static const  onVideoClosed :String= "onVideoClosed";
		public static const  onVideoPresent:String = "onVideoPresent";
		public static const  onVideoCompleted :String= "onVideoCompleted";
		public static const  onVideoStarted :String= "onVideoStarted";
		
		public var data:Object;
		public function UnityAdsEvent(type:String,data:*=null, bubbles:Boolean=false, cancelable:Boolean=false)
		{
			super(type, bubbles, cancelable);
			this.data=data;
		}
	}
}

**Comment by Gamezhero** [comment]
no, no 

u3d.isVideoReady() is true and I see UnityAdsEvent.onLoadVideoSuccess before, but don't see result on u3d.showVideo(); don't any events, don't traces... 

All work great with same code on Android & iOs (reward & video ads)
besides video ads (u3d.showVideo())  on Android

**Comment by Gamezhero** [comment]
up

**Comment by Jacowaco** [comment]
The same happens to me, showRewardVideo() work perfect, but showVideo() doesn't work.
I added event listener to every UnityAdsEvent type there is but nothing is being traced.

**Comment by lilili87222** [comment]
fixed
