### ISSUE TITLE
How to fetch rewarded ad?

### ISSUE THREAD

**Issue by RamyDergham** [lilili87222/Unity-ANE#3]
So I had an issue after showing 3 to 4 ads , the isVideoReady() method turns to false and never turn to true again . So is there a way to fetch rewarded ads again and catch the onAdReceived event?

**Comment by lilili87222** [comment]
Unity no such api.

**Comment by RamyDergham** [comment]
So what should I do when isVideoReady() returns false? Wait and check later?

**Comment by RamyDergham** [comment]
?? The problem that after showing 3-4 ads i can't show anymore ads unless i restart the app , is that normal ?

**Comment by lilili87222** [comment]
I think that is normal.Unity ad not load api to fetch ad.only wait.
