### ISSUE TITLE
showRewardVideo() disappeared?

### ISSUE THREAD

**Issue by Jacowaco** [lilili87222/Unity-ANE#6]
Hi, i no longer see the method showRewardVideo(), i only see showVideo().
What happened?

**Comment by lilili87222** [comment]
if your placement id is reward video,then you will show reward video.

**Comment by Jacowaco** [comment]
Thanks! That answered my question.

**Comment by kadirakkus9** [comment]
Hi;
u3d.addEventListener(UnityAdsEvent.onLoadVideoSuccess,onAdReceived);
This Code Works No Difficulty.
But it's always showing ads. I close the ad, it is always open again.
I Want You To Show It Once When Every Code Works.

u3d.addEventListener(UnityAdsEvent.onVideoStarted,onAdReceived);
This code does not work.
He never shows the ad.

Event I want to do u3d.showVideo (); When I Run the Code I Just Want You To Advertise 1 Time.

Please help me. How I Can Solve This Problem.
